management:
  health:
    diskspace:
      enabled: "true"
    default:
      enabled: "true"
    db:
      enabled: "true"
  servlet:
    context-path: /manage
spa:
  default-file: /dist/index.html
spring:
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: "false"
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password:
      username:
    url:
  data:
    web:
      pageable:
        one-indexed-parameters: "true"
  mvc:
    throw-exception-if-no-handler-found: "true"
  devtools:
    livereload:
      enabled: "true"
  mail:
    host: smtp.gmail.com
    port:
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  redis:
    host:
    port:
logging:
  level:
    org:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.boot: DEBUG
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      apache:
        tiles: INFO
    root: INFO
    com:
      samsung:
        security: DEBUG
  file:
    name: ./ssafy-web.log
server:
  servlet:
    encoding:
      enabled: "true"
      force: "true"
      charset: UTF-8
    contextPath: /api
  address: 0.0.0.0
  port: ""
  compression:
    enabled: "true"
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
build:
  date: "@build.date@"
jwt:
  expiration: ""
  cookieName:
  secret:
springfox:
  documentation:
    swagger:
      use-model-v3: "false"
openvidu:
  url: ""
  secret: ""
